-- Auto-paper cron: founder-mode dataset collection.
-- Started by Phase 2. Tables track the lifecycle of trades the cron opens
-- automatically against a hardcoded watchlist, plus daily mark-to-market
-- snapshots. Designed to be queryable both for the /auto-paper UI and for
-- future analytics (calibration, regime detection, etc.).
--
-- device_id for auto-paper picks is the synthetic constant 'auto_paper_founder'
-- so they appear alongside user picks in the shared /calibration dashboard
-- but are clearly segregatable via `ticker LIKE 'auto:%'` if needed.

CREATE TABLE IF NOT EXISTS auto_paper_picks (
  id                  TEXT    PRIMARY KEY,             -- ULID-ish, generated by the cron
  ticker              TEXT    NOT NULL,
  strategy_id         TEXT    NOT NULL,                -- matches lib/strategies.ts StrategyId
  opened_at           TEXT    NOT NULL,                -- ISO8601
  spot_at_open        REAL    NOT NULL,                -- $/share at open
  sigma_at_open       REAL    NOT NULL,                -- annualized realized vol at open
  iv_rank_at_open     REAL    NOT NULL,                -- 0..100
  dte                 INTEGER NOT NULL,                -- days to expiry at open
  contracts           INTEGER NOT NULL DEFAULT 1,      -- # of contracts opened
  predicted_pop       REAL    NOT NULL,                -- 0..1 (MC)
  predicted_pnl       REAL    NOT NULL,                -- $/contract, model estimate
  predicted_maxloss   REAL    NOT NULL,                -- $/contract (positive)
  max_profit          REAL    NOT NULL,                -- $/contract (positive)
  status              TEXT    NOT NULL DEFAULT 'open', -- 'open' | 'closed' | 'expired'
  closed_at           TEXT,                           -- ISO8601
  close_spot          REAL,                           -- $/share at close
  close_per_contract  REAL,                           -- $/contract cash flow at close
  realized_pnl        REAL,                           -- $/contract × q (or +entry+close for credits)
  close_reason        TEXT,                           -- 'profit_target' | 'stop_loss' | 'expiry' | 'manual'
  legs_json           TEXT    NOT NULL,                -- JSON-encoded Leg[] (snapshot at open)
  notes               TEXT
);

CREATE INDEX IF NOT EXISTS idx_app_status_opened
  ON auto_paper_picks (status, opened_at);
CREATE INDEX IF NOT EXISTS idx_app_ticker
  ON auto_paper_picks (ticker);
CREATE INDEX IF NOT EXISTS idx_app_strategy
  ON auto_paper_picks (strategy_id);

CREATE TABLE IF NOT EXISTS auto_paper_marks (
  id               TEXT    PRIMARY KEY,                 -- ULID-ish
  pick_id          TEXT    NOT NULL,
  marked_at        TEXT    NOT NULL,                    -- ISO8601
  spot             REAL    NOT NULL,                    -- $/share
  sigma            REAL    NOT NULL,                    -- annualized realized vol at mark time
  remaining_dte    REAL    NOT NULL,                    -- days to expiry (fractional)
  mtm_per_contract REAL    NOT NULL,                    -- $/contract
  unrealized_pnl   REAL    NOT NULL,                    -- total $ across contracts (signed)
  FOREIGN KEY (pick_id) REFERENCES auto_paper_picks(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_apm_pick_time
  ON auto_paper_marks (pick_id, marked_at);

-- A small audit log so we can see why the cron did or didn't act.
CREATE TABLE IF NOT EXISTS auto_paper_runs (
  id              TEXT    PRIMARY KEY,
  ran_at          TEXT    NOT NULL,                     -- ISO8601
  kind            TEXT    NOT NULL,                     -- 'open' | 'mark' | 'close_expired'
  tickers_seen    INTEGER NOT NULL,
  picks_opened    INTEGER NOT NULL DEFAULT 0,
  picks_marked    INTEGER NOT NULL DEFAULT 0,
  picks_closed    INTEGER NOT NULL DEFAULT 0,
  errors          TEXT,                                -- JSON array of {ticker, reason}
  duration_ms     INTEGER
);

CREATE INDEX IF NOT EXISTS idx_apr_ran_at
  ON auto_paper_runs (ran_at DESC);